introduce github actions
syseleven/designate-certmanager-webhook pull request #79
Opened 2022-04-20 14:45 UTC by xetys

2022-04-22 12:46 UTC, squ94wk commented
please rebase onto master. I just merged the Dockerfile MR.

2022-04-22 13:22 UTC, furkhat requested changes
two minor things, overall LGTM

2022-04-22 13:22 UTC, furkhat commented on go.mod
> +	github.com/fsnotify/fsnotify v1.5.1 // indirect
it looks like it needs `go mod tidy`

2022-04-22 13:22 UTC, furkhat commented on main.go
> +	"github.com/cert-manager/cert-manager/pkg/acme/webhook"
Let's move this import down so it is next to other `cert-manager` imports

2022-04-22 13:44 UTC, xetys commented on go.mod
> +	github.com/fsnotify/fsnotify v1.5.1 // indirect
it doesn't change if I do that

2022-04-25 05:45 UTC, furkhat approved these changes

2022-04-25 09:16 UTC, merged